"""whole db

Revision ID: 150cc2b6c2f2
Revises: 793d76ce923c
Create Date: 2022-02-11 17:55:31.217348

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '150cc2b6c2f2'
down_revision = '793d76ce923c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('username', sa.String(), nullable=False),
    sa.Column('password', sa.String(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    op.create_table('atends',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('meetup_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['meetup_id'], ['meetups.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'meetup_id')
    )
    op.add_column('meetups', sa.Column('address', sa.String(), nullable=False))
    op.add_column('meetups', sa.Column('published', sa.Boolean(), server_default='True', nullable=False))
    op.add_column('meetups', sa.Column('price', sa.Integer(), nullable=True))
    op.add_column('meetups', sa.Column('limit', sa.Integer(), nullable=True))
    op.add_column('meetups', sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.add_column('meetups', sa.Column('organizer_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'meetups', 'users', ['organizer_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'meetups', type_='foreignkey')
    op.drop_column('meetups', 'organizer_id')
    op.drop_column('meetups', 'created_at')
    op.drop_column('meetups', 'limit')
    op.drop_column('meetups', 'price')
    op.drop_column('meetups', 'published')
    op.drop_column('meetups', 'address')
    op.drop_table('atends')
    op.drop_table('users')
    # ### end Alembic commands ###
